name: "Mark Higginson"
description: "The web is a social artifact. Here is a selected collection of related items."

url: "http://markhigginson.co.uk/"

paginate: 5

markdown: rdiscount
permalink: pretty