name: "Mark Higginson"
description: "The web is a social artifact. Here is a selected collection of related items."

url: "http://markhgn.github.io/"

paginate: 5

markdown: rdiscount
permalink: pretty